### ISSUE TITLE
Remove old branches to avoid confusion

### ISSUE THREAD

**Issue by asomov** [AsynkronIT/protoactor-kotlin#53]
Can you please remove branches which were merged:
remotes/origin/update-to-jdk 
rmotes/origin/router
remotes/origin/implicit-context
remotes/origin/300mil 
remotes/origin/reformat
remotes/origin/racy-routers

Can these be removed because Kotlin 1.3 is used already ?
  remotes/origin/kotlin-1.1.3-2      
  remotes/origin/kotlin-1.1.4-eap-33
  remotes/origin/kotlin-1.2-M1

These look like old because Gradle is already used:
remotes/origin/revert-3-gradle
remotes/origin/gradle

**Comment by orjan** [comment]
I've removed all branches except master!

I'd a look at the branches and forked:
https://github.com/orjan/protoactor-kotlin/tree/kotlin-1.1.4-eap-33
https://github.com/orjan/protoactor-kotlin/tree/gradle

Since there are some commits that might be useful even if I doubt like this one, that's not part of the master branch: https://github.com/orjan/protoactor-kotlin/commit/0112a20091c538422d656ee2c697dce983cb7340
